; ModuleID = 'circuit-144'
source_filename = "circuit-144"

%Qubit = type opaque
%Result = type opaque

define void @circuit-144() #0 {
entry:
  call void @__quantum__rt__initialize(i8* null)
  call void @__quantum__qis__ry__body(double 0xC002D97C7F3321D2, %Qubit* null)
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* null)
  call void @__quantum__qis__ry__body(double 0xC004357AB3F5C37E, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC004F1A6C638D03F, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0056C6E70C66ED2, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC005C4BA39F29D2E, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006082F03C91575, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0063DE6E11A94C4, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC00669FEE7A19782, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0068F0963259C5F, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006AEB9CCE55399, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006CA3D666267C1, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006E26C16791B62, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006F7E55A31D7D6, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0070B219F5C8452, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0071C7E1DE29C2F, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0072C43F923A005, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0073AADA66663CF, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC00747EA8AF340C2, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0075421580EE7E7, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0075F723EB148D0, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC00769F82438F785, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC00773C9A16EAD49, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0077CFA0188C954, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0078599C8630DD9, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0078DB738B65D0B, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC007955E973497A4, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__x__body(%Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 26 to %Qubit*), %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC007955E973497A4, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 25 to %Qubit*), %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0078DB738B65D0B, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0078599C8630DD9, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0077CFA0188C954, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC00773C9A16EAD49, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC00769F82438F785, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0075F723EB148D0, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0075421580EE7E7, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC00747EA8AF340C2, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0073AADA66663CF, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0072C43F923A005, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0071C7E1DE29C2F, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0070B219F5C8452, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006F7E55A31D7D6, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006E26C16791B62, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006CA3D666267C1, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 25 to %Qubit*), %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006AEB9CCE55399, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0068F0963259C5F, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC00669FEE7A19782, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0063DE6E11A94C4, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC006082F03C91575, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC005C4BA39F29D2E, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC0056C6E70C66ED2, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC004F1A6C638D03F, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xC004357AB3F5C37E, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Qubit* null)
  call void @__quantum__qis__ry__body(double 0xC002D97C7F3321D2, %Qubit* null)
  call void @__quantum__qis__rz__body(double 0xC00921FB54442D18, %Qubit* null)
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__mz__body(%Qubit* null, %Result* inttoptr (i64 27 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Result* inttoptr (i64 28 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Result* inttoptr (i64 29 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Result* inttoptr (i64 30 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Result* inttoptr (i64 31 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Result* inttoptr (i64 32 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Result* inttoptr (i64 33 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Result* inttoptr (i64 34 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Result* inttoptr (i64 35 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Result* inttoptr (i64 36 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Result* inttoptr (i64 37 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Result* inttoptr (i64 38 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Result* inttoptr (i64 39 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Result* inttoptr (i64 40 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Result* inttoptr (i64 41 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Result* inttoptr (i64 42 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Result* inttoptr (i64 43 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Result* inttoptr (i64 44 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Result* inttoptr (i64 45 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Result* inttoptr (i64 46 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Result* inttoptr (i64 47 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Result* inttoptr (i64 48 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Result* inttoptr (i64 49 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Result* inttoptr (i64 50 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Result* inttoptr (i64 51 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 25 to %Qubit*), %Result* inttoptr (i64 52 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 26 to %Qubit*), %Result* inttoptr (i64 53 to %Result*))
  call void @__quantum__rt__array_record_output(i64 27, i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 26 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 25 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 24 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 23 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 22 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 21 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 20 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 19 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 18 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 17 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 16 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 15 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 14 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 13 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 12 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 11 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 10 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 9 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 8 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 7 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 6 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 5 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 4 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 3 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 2 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 1 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* null, i8* null)
  call void @__quantum__rt__array_record_output(i64 27, i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 53 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 52 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 51 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 50 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 49 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 48 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 47 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 46 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 45 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 44 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 43 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 42 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 41 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 40 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 39 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 38 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 37 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 36 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 35 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 34 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 33 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 32 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 31 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 30 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 29 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 28 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 27 to %Result*), i8* null)
  ret void
}

declare void @__quantum__rt__initialize(i8*)

declare void @__quantum__qis__ry__body(double, %Qubit*)

declare void @__quantum__qis__rz__body(double, %Qubit*)

declare void @__quantum__qis__x__body(%Qubit*)

declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)

declare void @__quantum__qis__mz__body(%Qubit*, %Result* writeonly) #1

declare void @__quantum__rt__array_record_output(i64, i8*)

declare void @__quantum__rt__result_record_output(%Result*, i8*)

attributes #0 = { "entry_point" "num_required_qubits"="27" "num_required_results"="54" "output_labeling_schema" "qir_profiles"="custom" }
attributes #1 = { "irreversible" }
