; ModuleID = 'circuit-136'
source_filename = "circuit-136"

%Qubit = type opaque
%Result = type opaque

define void @circuit-136() #0 {
entry:
  call void @__quantum__rt__initialize(i8* null)
  call void @__quantum__qis__h__body(%Qubit* null)
  call void @__quantum__qis__ry__body(double 0x3FF0587EB1B6C6D1, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FC6AE42B383D085, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FCF7929771CC203, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FD7EAC81FE9D546, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF7A13E59012316, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FC556DFCB2C38C3, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FEE5F3BCFB9E717, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FD82E8FEB1A14D4, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF9528ACC773C77, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4005F0932AEA8F55, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF0330D3DD62464, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF716A238A48C3C, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FEA135EA72A50E1, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FB4B5DF7570F058, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF3CF5019F3C70D, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4005AC1EC9EFA2BB, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FE40EE31CC55D98, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__ry__body(double 1.802550e-01, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FD6CD225D221A06, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FFAE62710E60151, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FDFA605F91351C1, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4004F3C36E7F399C, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FFED63ABA1031A6, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x40090316C8996165, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x40065B87F37EE83D, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FFEE89A38250A7C, %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF90DE7B4AF9F95, %Qubit* inttoptr (i64 27 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x40047E05B1F0A874, %Qubit* inttoptr (i64 28 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4000BA7447D0792A, %Qubit* inttoptr (i64 29 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4003FFAF85942917, %Qubit* inttoptr (i64 30 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FE51DA3A9E8C729, %Qubit* inttoptr (i64 31 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x40042A65DCD3AB0D, %Qubit* inttoptr (i64 32 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FDD53D08C9FE106, %Qubit* inttoptr (i64 33 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FE4DC3B3F463BFA, %Qubit* inttoptr (i64 34 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 34 to %Qubit*), %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 1 to %Qubit*), %Qubit* inttoptr (i64 34 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 34 to %Qubit*), %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF27BA450ACC0BE, %Qubit* inttoptr (i64 35 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 35 to %Qubit*), %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 2 to %Qubit*), %Qubit* inttoptr (i64 35 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 35 to %Qubit*), %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3F9FED373F4B3349, %Qubit* inttoptr (i64 36 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 36 to %Qubit*), %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 3 to %Qubit*), %Qubit* inttoptr (i64 36 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 36 to %Qubit*), %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FFBDF63A84604C7, %Qubit* inttoptr (i64 37 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 37 to %Qubit*), %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 4 to %Qubit*), %Qubit* inttoptr (i64 37 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 37 to %Qubit*), %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x40057579E4C86C15, %Qubit* inttoptr (i64 38 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 38 to %Qubit*), %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 5 to %Qubit*), %Qubit* inttoptr (i64 38 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 38 to %Qubit*), %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF925BF9251A6BC, %Qubit* inttoptr (i64 39 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 39 to %Qubit*), %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 6 to %Qubit*), %Qubit* inttoptr (i64 39 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 39 to %Qubit*), %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FC135B8891DF660, %Qubit* inttoptr (i64 40 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 40 to %Qubit*), %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 7 to %Qubit*), %Qubit* inttoptr (i64 40 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 40 to %Qubit*), %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x40088D15AD106EE3, %Qubit* inttoptr (i64 41 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 41 to %Qubit*), %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 8 to %Qubit*), %Qubit* inttoptr (i64 41 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 41 to %Qubit*), %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x40019BB5EE63F64A, %Qubit* inttoptr (i64 42 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 42 to %Qubit*), %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 9 to %Qubit*), %Qubit* inttoptr (i64 42 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 42 to %Qubit*), %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FA8AE02D4930C2E, %Qubit* inttoptr (i64 43 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 43 to %Qubit*), %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 10 to %Qubit*), %Qubit* inttoptr (i64 43 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 43 to %Qubit*), %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__ry__body(double 2.533120e-01, %Qubit* inttoptr (i64 44 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 44 to %Qubit*), %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 11 to %Qubit*), %Qubit* inttoptr (i64 44 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 44 to %Qubit*), %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF57E9F425006A9, %Qubit* inttoptr (i64 45 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 45 to %Qubit*), %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 12 to %Qubit*), %Qubit* inttoptr (i64 45 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 45 to %Qubit*), %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6960326FBED4C, %Qubit* inttoptr (i64 46 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 46 to %Qubit*), %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 13 to %Qubit*), %Qubit* inttoptr (i64 46 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 46 to %Qubit*), %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FFD89D13A19D742, %Qubit* inttoptr (i64 47 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 47 to %Qubit*), %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 14 to %Qubit*), %Qubit* inttoptr (i64 47 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 47 to %Qubit*), %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF3FD0A16DA3719, %Qubit* inttoptr (i64 48 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 48 to %Qubit*), %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 15 to %Qubit*), %Qubit* inttoptr (i64 48 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 48 to %Qubit*), %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF0E4D8ACD4DFC1, %Qubit* inttoptr (i64 49 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 49 to %Qubit*), %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 16 to %Qubit*), %Qubit* inttoptr (i64 49 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 49 to %Qubit*), %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4004B2A4B2D24FC4, %Qubit* inttoptr (i64 50 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 50 to %Qubit*), %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 17 to %Qubit*), %Qubit* inttoptr (i64 50 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 50 to %Qubit*), %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4000CEC311622813, %Qubit* inttoptr (i64 51 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 51 to %Qubit*), %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 18 to %Qubit*), %Qubit* inttoptr (i64 51 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 51 to %Qubit*), %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF8E8794B4578B0, %Qubit* inttoptr (i64 52 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 52 to %Qubit*), %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 19 to %Qubit*), %Qubit* inttoptr (i64 52 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 52 to %Qubit*), %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x40025AB5EBDFB78B, %Qubit* inttoptr (i64 53 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 53 to %Qubit*), %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 20 to %Qubit*), %Qubit* inttoptr (i64 53 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 53 to %Qubit*), %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4000FB81C3B9FE94, %Qubit* inttoptr (i64 54 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 54 to %Qubit*), %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 21 to %Qubit*), %Qubit* inttoptr (i64 54 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 54 to %Qubit*), %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FFBBD40B856F403, %Qubit* inttoptr (i64 55 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 55 to %Qubit*), %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 22 to %Qubit*), %Qubit* inttoptr (i64 55 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 55 to %Qubit*), %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FC0CD7DCCB47919, %Qubit* inttoptr (i64 56 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 56 to %Qubit*), %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 23 to %Qubit*), %Qubit* inttoptr (i64 56 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 56 to %Qubit*), %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FDC07F0CFB66126, %Qubit* inttoptr (i64 57 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 57 to %Qubit*), %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 24 to %Qubit*), %Qubit* inttoptr (i64 57 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 57 to %Qubit*), %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FBCA65A1C5621F6, %Qubit* inttoptr (i64 58 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 58 to %Qubit*), %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 25 to %Qubit*), %Qubit* inttoptr (i64 58 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 58 to %Qubit*), %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF4A5AF0109EB3B, %Qubit* inttoptr (i64 59 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 59 to %Qubit*), %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 26 to %Qubit*), %Qubit* inttoptr (i64 59 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 59 to %Qubit*), %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4005048C494EFE6B, %Qubit* inttoptr (i64 60 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 60 to %Qubit*), %Qubit* inttoptr (i64 27 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 27 to %Qubit*), %Qubit* inttoptr (i64 60 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 60 to %Qubit*), %Qubit* inttoptr (i64 27 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF9B71ECAC66250, %Qubit* inttoptr (i64 61 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 61 to %Qubit*), %Qubit* inttoptr (i64 28 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 28 to %Qubit*), %Qubit* inttoptr (i64 61 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 61 to %Qubit*), %Qubit* inttoptr (i64 28 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4004F7DEAE76A070, %Qubit* inttoptr (i64 62 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 62 to %Qubit*), %Qubit* inttoptr (i64 29 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 29 to %Qubit*), %Qubit* inttoptr (i64 62 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 62 to %Qubit*), %Qubit* inttoptr (i64 29 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x4006536F12DD5256, %Qubit* inttoptr (i64 63 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 63 to %Qubit*), %Qubit* inttoptr (i64 30 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 30 to %Qubit*), %Qubit* inttoptr (i64 63 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 63 to %Qubit*), %Qubit* inttoptr (i64 30 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FEE77F7B8B3BB2E, %Qubit* inttoptr (i64 64 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 64 to %Qubit*), %Qubit* inttoptr (i64 31 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 31 to %Qubit*), %Qubit* inttoptr (i64 64 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 64 to %Qubit*), %Qubit* inttoptr (i64 31 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF08A2C59245E84, %Qubit* inttoptr (i64 65 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 65 to %Qubit*), %Qubit* inttoptr (i64 32 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 32 to %Qubit*), %Qubit* inttoptr (i64 65 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 65 to %Qubit*), %Qubit* inttoptr (i64 32 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FFBE09A24031487, %Qubit* inttoptr (i64 66 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 66 to %Qubit*), %Qubit* inttoptr (i64 33 to %Qubit*))
  call void @__quantum__qis__ccx__body(%Qubit* null, %Qubit* inttoptr (i64 33 to %Qubit*), %Qubit* inttoptr (i64 66 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* null)
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 66 to %Qubit*), %Qubit* inttoptr (i64 33 to %Qubit*))
  call void @__quantum__qis__mz__body(%Qubit* null, %Result* null)
  call void @__quantum__rt__array_record_output(i64 1, i8* null)
  call void @__quantum__rt__result_record_output(%Result* null, i8* null)
  ret void
}

declare void @__quantum__rt__initialize(i8*)

declare void @__quantum__qis__h__body(%Qubit*)

declare void @__quantum__qis__ry__body(double, %Qubit*)

declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)

declare void @__quantum__qis__ccx__body(%Qubit*, %Qubit*, %Qubit*)

declare void @__quantum__qis__mz__body(%Qubit*, %Result* writeonly) #1

declare void @__quantum__rt__array_record_output(i64, i8*)

declare void @__quantum__rt__result_record_output(%Result*, i8*)

attributes #0 = { "entry_point" "num_required_qubits"="67" "num_required_results"="1" "output_labeling_schema" "qir_profiles"="custom" }
attributes #1 = { "irreversible" }
