; ModuleID = 'circuit-79261'
source_filename = "circuit-79261"

%Qubit = type opaque
%Result = type opaque

define void @circuit-79261() #0 {
entry:
  call void @__quantum__rt__initialize(i8* null)
  call void @__quantum__qis__ry__body(double 0xBFE921FB54442D18, %Qubit* null)
  call void @__quantum__qis__ry__body(double 0xBFEE91F42805715D, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF0C152382D7365, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF1B6E192EBBE44, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF267791E35F0C4, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF2EE62BEF09FF2, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF359D26F93B6C3, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF3B2028082E8D4, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF3FC176B7A8560, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF43B783B02C1FD, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF4727F6D4D118C, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF4A2DCE0545978, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF4CDCF57453D63, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF4F447EF953118, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF51700E0C14B25, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF5368C951E9CFC, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF5535FF9EBDE75, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF56DD9B883EAB8, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF586476251E745, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF59CE9373D5964, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF5B1F4F35A6571, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF5C597EC29CE8E, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF5D7F8AE7D99FA, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF5E9383EFAD0D0, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF5F97315254856, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF608C1E2140F17, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6173A2F3C1736, %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF624EEDE759DF1, %Qubit* inttoptr (i64 27 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF631F0920B2D7E, %Qubit* inttoptr (i64 28 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF63E4E01F2BB9F, %Qubit* inttoptr (i64 29 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF64A144217A8F0, %Qubit* inttoptr (i64 30 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6554EFCB50860, %Qubit* inttoptr (i64 31 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF66008A313275C, %Qubit* inttoptr (i64 32 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF66A4A967983A2, %Qubit* inttoptr (i64 33 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6741D4AC3C036, %Qubit* inttoptr (i64 34 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF67D8863BC99BC, %Qubit* inttoptr (i64 35 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF68692CE27789B, %Qubit* inttoptr (i64 36 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF68F42D533CB81, %Qubit* inttoptr (i64 37 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6979E34F1B091, %Qubit* inttoptr (i64 38 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF69FAA2A434FCC, %Qubit* inttoptr (i64 39 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6A76B80AFED38, %Qubit* inttoptr (i64 40 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6AEE69E6BD934, %Qubit* inttoptr (i64 41 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6B61F8EDA05D9, %Qubit* inttoptr (i64 42 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6BD1A0BC06968, %Qubit* inttoptr (i64 43 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6C3D9855EE40C, %Qubit* inttoptr (i64 44 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6CA612990A880, %Qubit* inttoptr (i64 45 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6D0B3EA19D29F, %Qubit* inttoptr (i64 46 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6D6D4823D9F2A, %Qubit* inttoptr (i64 47 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6DCC57BB565FC, %Qubit* inttoptr (i64 48 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6E289331CE0A6, %Qubit* inttoptr (i64 49 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6E821DBE54800, %Qubit* inttoptr (i64 50 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6ED9183DE508B, %Qubit* inttoptr (i64 51 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6F2DA1661F0E2, %Qubit* inttoptr (i64 52 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6F7FD5F2E1587, %Qubit* inttoptr (i64 53 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF6FCFD0CF5E35C, %Qubit* inttoptr (i64 54 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF701DAB3B2E211, %Qubit* inttoptr (i64 55 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF70697CEBD50BE, %Qubit* inttoptr (i64 56 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF70B35C2B1F808, %Qubit* inttoptr (i64 57 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF70FB5DF2B00D6, %Qubit* inttoptr (i64 58 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF714196050A6D3, %Qubit* inttoptr (i64 59 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF718617046069C, %Qubit* inttoptr (i64 60 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF71C8F2875C4BA, %Qubit* inttoptr (i64 61 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF720A392C1D954, %Qubit* inttoptr (i64 62 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF7249FAA996A21, %Qubit* inttoptr (i64 63 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF728845DF746C9, %Qubit* inttoptr (i64 64 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF72C528E4B5132, %Qubit* inttoptr (i64 65 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF7300B1150DA1D, %Qubit* inttoptr (i64 66 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF733AEB1D3C16E, %Qubit* inttoptr (i64 67 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF7373E3065F74D, %Qubit* inttoptr (i64 68 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF73ABA4406CF70, %Qubit* inttoptr (i64 69 to %Qubit*))
  call void @__quantum__qis__x__body(%Qubit* inttoptr (i64 70 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 70 to %Qubit*), %Qubit* inttoptr (i64 69 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF73ABA4406CF70, %Qubit* inttoptr (i64 69 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 69 to %Qubit*), %Qubit* inttoptr (i64 68 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF7373E3065F74D, %Qubit* inttoptr (i64 68 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 68 to %Qubit*), %Qubit* inttoptr (i64 67 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF733AEB1D3C16E, %Qubit* inttoptr (i64 67 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 67 to %Qubit*), %Qubit* inttoptr (i64 66 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF7300B1150DA1D, %Qubit* inttoptr (i64 66 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 66 to %Qubit*), %Qubit* inttoptr (i64 65 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF72C528E4B5132, %Qubit* inttoptr (i64 65 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 65 to %Qubit*), %Qubit* inttoptr (i64 64 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF728845DF746C9, %Qubit* inttoptr (i64 64 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 64 to %Qubit*), %Qubit* inttoptr (i64 63 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF7249FAA996A21, %Qubit* inttoptr (i64 63 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 63 to %Qubit*), %Qubit* inttoptr (i64 62 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF720A392C1D954, %Qubit* inttoptr (i64 62 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 62 to %Qubit*), %Qubit* inttoptr (i64 61 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF71C8F2875C4BA, %Qubit* inttoptr (i64 61 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 61 to %Qubit*), %Qubit* inttoptr (i64 60 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF718617046069C, %Qubit* inttoptr (i64 60 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 60 to %Qubit*), %Qubit* inttoptr (i64 59 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF714196050A6D3, %Qubit* inttoptr (i64 59 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 59 to %Qubit*), %Qubit* inttoptr (i64 58 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF70FB5DF2B00D6, %Qubit* inttoptr (i64 58 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 58 to %Qubit*), %Qubit* inttoptr (i64 57 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF70B35C2B1F808, %Qubit* inttoptr (i64 57 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 57 to %Qubit*), %Qubit* inttoptr (i64 56 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF70697CEBD50BE, %Qubit* inttoptr (i64 56 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 56 to %Qubit*), %Qubit* inttoptr (i64 55 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF701DAB3B2E211, %Qubit* inttoptr (i64 55 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 55 to %Qubit*), %Qubit* inttoptr (i64 54 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6FCFD0CF5E35C, %Qubit* inttoptr (i64 54 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 54 to %Qubit*), %Qubit* inttoptr (i64 53 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6F7FD5F2E1587, %Qubit* inttoptr (i64 53 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 53 to %Qubit*), %Qubit* inttoptr (i64 52 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6F2DA1661F0E2, %Qubit* inttoptr (i64 52 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 52 to %Qubit*), %Qubit* inttoptr (i64 51 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6ED9183DE508B, %Qubit* inttoptr (i64 51 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 51 to %Qubit*), %Qubit* inttoptr (i64 50 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6E821DBE54800, %Qubit* inttoptr (i64 50 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 50 to %Qubit*), %Qubit* inttoptr (i64 49 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6E289331CE0A6, %Qubit* inttoptr (i64 49 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 49 to %Qubit*), %Qubit* inttoptr (i64 48 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6DCC57BB565FC, %Qubit* inttoptr (i64 48 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 48 to %Qubit*), %Qubit* inttoptr (i64 47 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6D6D4823D9F2A, %Qubit* inttoptr (i64 47 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 47 to %Qubit*), %Qubit* inttoptr (i64 46 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6D0B3EA19D29F, %Qubit* inttoptr (i64 46 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 46 to %Qubit*), %Qubit* inttoptr (i64 45 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6CA612990A880, %Qubit* inttoptr (i64 45 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 45 to %Qubit*), %Qubit* inttoptr (i64 44 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6C3D9855EE40C, %Qubit* inttoptr (i64 44 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 44 to %Qubit*), %Qubit* inttoptr (i64 43 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6BD1A0BC06968, %Qubit* inttoptr (i64 43 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 43 to %Qubit*), %Qubit* inttoptr (i64 42 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6B61F8EDA05D9, %Qubit* inttoptr (i64 42 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 42 to %Qubit*), %Qubit* inttoptr (i64 41 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6AEE69E6BD934, %Qubit* inttoptr (i64 41 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 41 to %Qubit*), %Qubit* inttoptr (i64 40 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6A76B80AFED38, %Qubit* inttoptr (i64 40 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 40 to %Qubit*), %Qubit* inttoptr (i64 39 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF69FAA2A434FCC, %Qubit* inttoptr (i64 39 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 39 to %Qubit*), %Qubit* inttoptr (i64 38 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6979E34F1B091, %Qubit* inttoptr (i64 38 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 38 to %Qubit*), %Qubit* inttoptr (i64 37 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF68F42D533CB81, %Qubit* inttoptr (i64 37 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 37 to %Qubit*), %Qubit* inttoptr (i64 36 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF68692CE27789B, %Qubit* inttoptr (i64 36 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 36 to %Qubit*), %Qubit* inttoptr (i64 35 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF67D8863BC99BC, %Qubit* inttoptr (i64 35 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 35 to %Qubit*), %Qubit* inttoptr (i64 34 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6741D4AC3C036, %Qubit* inttoptr (i64 34 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 34 to %Qubit*), %Qubit* inttoptr (i64 33 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF66A4A967983A2, %Qubit* inttoptr (i64 33 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 33 to %Qubit*), %Qubit* inttoptr (i64 32 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF66008A313275C, %Qubit* inttoptr (i64 32 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 32 to %Qubit*), %Qubit* inttoptr (i64 31 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6554EFCB50860, %Qubit* inttoptr (i64 31 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 31 to %Qubit*), %Qubit* inttoptr (i64 30 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF64A144217A8F0, %Qubit* inttoptr (i64 30 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 30 to %Qubit*), %Qubit* inttoptr (i64 29 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF63E4E01F2BB9F, %Qubit* inttoptr (i64 29 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 29 to %Qubit*), %Qubit* inttoptr (i64 28 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF631F0920B2D7E, %Qubit* inttoptr (i64 28 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 28 to %Qubit*), %Qubit* inttoptr (i64 27 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF624EEDE759DF1, %Qubit* inttoptr (i64 27 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 27 to %Qubit*), %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF6173A2F3C1736, %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 26 to %Qubit*), %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF608C1E2140F17, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 25 to %Qubit*), %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF5F97315254856, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF5E9383EFAD0D0, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF5D7F8AE7D99FA, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF5C597EC29CE8E, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF5B1F4F35A6571, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF59CE9373D5964, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF586476251E745, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF56DD9B883EAB8, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF5535FF9EBDE75, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF5368C951E9CFC, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF51700E0C14B25, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF4F447EF953118, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF4CDCF57453D63, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF4A2DCE0545978, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF4727F6D4D118C, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 69 to %Qubit*), %Qubit* inttoptr (i64 70 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 68 to %Qubit*), %Qubit* inttoptr (i64 69 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 67 to %Qubit*), %Qubit* inttoptr (i64 68 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 66 to %Qubit*), %Qubit* inttoptr (i64 67 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 65 to %Qubit*), %Qubit* inttoptr (i64 66 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 64 to %Qubit*), %Qubit* inttoptr (i64 65 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 63 to %Qubit*), %Qubit* inttoptr (i64 64 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 62 to %Qubit*), %Qubit* inttoptr (i64 63 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 61 to %Qubit*), %Qubit* inttoptr (i64 62 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 60 to %Qubit*), %Qubit* inttoptr (i64 61 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 59 to %Qubit*), %Qubit* inttoptr (i64 60 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 58 to %Qubit*), %Qubit* inttoptr (i64 59 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 57 to %Qubit*), %Qubit* inttoptr (i64 58 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 56 to %Qubit*), %Qubit* inttoptr (i64 57 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 55 to %Qubit*), %Qubit* inttoptr (i64 56 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 54 to %Qubit*), %Qubit* inttoptr (i64 55 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 53 to %Qubit*), %Qubit* inttoptr (i64 54 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 52 to %Qubit*), %Qubit* inttoptr (i64 53 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 51 to %Qubit*), %Qubit* inttoptr (i64 52 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 50 to %Qubit*), %Qubit* inttoptr (i64 51 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 49 to %Qubit*), %Qubit* inttoptr (i64 50 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 48 to %Qubit*), %Qubit* inttoptr (i64 49 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 47 to %Qubit*), %Qubit* inttoptr (i64 48 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 46 to %Qubit*), %Qubit* inttoptr (i64 47 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 45 to %Qubit*), %Qubit* inttoptr (i64 46 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 44 to %Qubit*), %Qubit* inttoptr (i64 45 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 43 to %Qubit*), %Qubit* inttoptr (i64 44 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 42 to %Qubit*), %Qubit* inttoptr (i64 43 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 41 to %Qubit*), %Qubit* inttoptr (i64 42 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 40 to %Qubit*), %Qubit* inttoptr (i64 41 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 39 to %Qubit*), %Qubit* inttoptr (i64 40 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 38 to %Qubit*), %Qubit* inttoptr (i64 39 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 37 to %Qubit*), %Qubit* inttoptr (i64 38 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 36 to %Qubit*), %Qubit* inttoptr (i64 37 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 35 to %Qubit*), %Qubit* inttoptr (i64 36 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 34 to %Qubit*), %Qubit* inttoptr (i64 35 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 33 to %Qubit*), %Qubit* inttoptr (i64 34 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 32 to %Qubit*), %Qubit* inttoptr (i64 33 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 31 to %Qubit*), %Qubit* inttoptr (i64 32 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 30 to %Qubit*), %Qubit* inttoptr (i64 31 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 29 to %Qubit*), %Qubit* inttoptr (i64 30 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 28 to %Qubit*), %Qubit* inttoptr (i64 29 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 27 to %Qubit*), %Qubit* inttoptr (i64 28 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 26 to %Qubit*), %Qubit* inttoptr (i64 27 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 25 to %Qubit*), %Qubit* inttoptr (i64 26 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF43B783B02C1FD, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF3FC176B7A8560, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF3B2028082E8D4, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF359D26F93B6C3, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF2EE62BEF09FF2, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF267791E35F0C4, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF1B6E192EBBE44, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FF0C152382D7365, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0x3FEE91F42805715D, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__cz__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Qubit* null)
  call void @__quantum__qis__ry__body(double 0x3FE921FB54442D18, %Qubit* null)
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__mz__body(%Qubit* null, %Result* null)
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Result* inttoptr (i64 1 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Result* inttoptr (i64 2 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Result* inttoptr (i64 3 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Result* inttoptr (i64 4 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Result* inttoptr (i64 5 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Result* inttoptr (i64 6 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Result* inttoptr (i64 7 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Result* inttoptr (i64 8 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Result* inttoptr (i64 9 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Result* inttoptr (i64 10 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Result* inttoptr (i64 11 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Result* inttoptr (i64 12 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Result* inttoptr (i64 13 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Result* inttoptr (i64 14 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Result* inttoptr (i64 15 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Result* inttoptr (i64 16 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Result* inttoptr (i64 17 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Result* inttoptr (i64 18 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Result* inttoptr (i64 19 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Result* inttoptr (i64 20 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Result* inttoptr (i64 21 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Result* inttoptr (i64 22 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Result* inttoptr (i64 23 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Result* inttoptr (i64 24 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 25 to %Qubit*), %Result* inttoptr (i64 25 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 26 to %Qubit*), %Result* inttoptr (i64 26 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 27 to %Qubit*), %Result* inttoptr (i64 27 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 28 to %Qubit*), %Result* inttoptr (i64 28 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 29 to %Qubit*), %Result* inttoptr (i64 29 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 30 to %Qubit*), %Result* inttoptr (i64 30 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 31 to %Qubit*), %Result* inttoptr (i64 31 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 32 to %Qubit*), %Result* inttoptr (i64 32 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 33 to %Qubit*), %Result* inttoptr (i64 33 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 34 to %Qubit*), %Result* inttoptr (i64 34 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 35 to %Qubit*), %Result* inttoptr (i64 35 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 36 to %Qubit*), %Result* inttoptr (i64 36 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 37 to %Qubit*), %Result* inttoptr (i64 37 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 38 to %Qubit*), %Result* inttoptr (i64 38 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 39 to %Qubit*), %Result* inttoptr (i64 39 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 40 to %Qubit*), %Result* inttoptr (i64 40 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 41 to %Qubit*), %Result* inttoptr (i64 41 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 42 to %Qubit*), %Result* inttoptr (i64 42 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 43 to %Qubit*), %Result* inttoptr (i64 43 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 44 to %Qubit*), %Result* inttoptr (i64 44 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 45 to %Qubit*), %Result* inttoptr (i64 45 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 46 to %Qubit*), %Result* inttoptr (i64 46 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 47 to %Qubit*), %Result* inttoptr (i64 47 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 48 to %Qubit*), %Result* inttoptr (i64 48 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 49 to %Qubit*), %Result* inttoptr (i64 49 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 50 to %Qubit*), %Result* inttoptr (i64 50 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 51 to %Qubit*), %Result* inttoptr (i64 51 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 52 to %Qubit*), %Result* inttoptr (i64 52 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 53 to %Qubit*), %Result* inttoptr (i64 53 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 54 to %Qubit*), %Result* inttoptr (i64 54 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 55 to %Qubit*), %Result* inttoptr (i64 55 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 56 to %Qubit*), %Result* inttoptr (i64 56 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 57 to %Qubit*), %Result* inttoptr (i64 57 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 58 to %Qubit*), %Result* inttoptr (i64 58 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 59 to %Qubit*), %Result* inttoptr (i64 59 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 60 to %Qubit*), %Result* inttoptr (i64 60 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 61 to %Qubit*), %Result* inttoptr (i64 61 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 62 to %Qubit*), %Result* inttoptr (i64 62 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 63 to %Qubit*), %Result* inttoptr (i64 63 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 64 to %Qubit*), %Result* inttoptr (i64 64 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 65 to %Qubit*), %Result* inttoptr (i64 65 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 66 to %Qubit*), %Result* inttoptr (i64 66 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 67 to %Qubit*), %Result* inttoptr (i64 67 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 68 to %Qubit*), %Result* inttoptr (i64 68 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 69 to %Qubit*), %Result* inttoptr (i64 69 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 70 to %Qubit*), %Result* inttoptr (i64 70 to %Result*))
  call void @__quantum__rt__array_record_output(i64 71, i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 70 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 69 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 68 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 67 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 66 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 65 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 64 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 63 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 62 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 61 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 60 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 59 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 58 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 57 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 56 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 55 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 54 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 53 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 52 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 51 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 50 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 49 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 48 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 47 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 46 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 45 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 44 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 43 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 42 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 41 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 40 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 39 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 38 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 37 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 36 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 35 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 34 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 33 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 32 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 31 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 30 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 29 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 28 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 27 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 26 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 25 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 24 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 23 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 22 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 21 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 20 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 19 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 18 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 17 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 16 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 15 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 14 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 13 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 12 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 11 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 10 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 9 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 8 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 7 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 6 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 5 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 4 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 3 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 2 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 1 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* null, i8* null)
  ret void
}

declare void @__quantum__rt__initialize(i8*)

declare void @__quantum__qis__ry__body(double, %Qubit*)

declare void @__quantum__qis__x__body(%Qubit*)

declare void @__quantum__qis__cz__body(%Qubit*, %Qubit*)

declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)

declare void @__quantum__qis__mz__body(%Qubit*, %Result* writeonly) #1

declare void @__quantum__rt__array_record_output(i64, i8*)

declare void @__quantum__rt__result_record_output(%Result*, i8*)

attributes #0 = { "entry_point" "num_required_qubits"="71" "num_required_results"="71" "output_labeling_schema" "qir_profiles"="custom" }
attributes #1 = { "irreversible" }
