; ModuleID = 'circuit-172'
source_filename = "circuit-172"

%Qubit = type opaque
%Result = type opaque

define void @circuit-172() #0 {
entry:
  call void @__quantum__rt__initialize(i8* null)
  call void @__quantum__qis__h__body(%Qubit* null)
  call void @__quantum__qis__rz__body(double 0xBFFC08C627971DBE, %Qubit* null)
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FD736569A978520, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFFC08C627971DBE, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* null, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FE39A6E70A0FCE5, %Qubit* inttoptr (i64 1 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF1ADCFE7338060, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFEDD0ADB442B2E0, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF1ADCFE7338060, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF39A6E70A0FCE4, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FE39A6E70A0FCE5, %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Qubit* inttoptr (i64 2 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFEB241CD54DCFC2, %Qubit* inttoptr (i64 3 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFE730A21ECE4C54, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFFB135489BA0DDC, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFE730A21ECE4C54, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FFB241CD54DCFC4, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFEB241CD54DCFC2, %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Qubit* inttoptr (i64 4 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FECB9505E115842, %Qubit* inttoptr (i64 5 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF6DC9F581F7BC6, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFD22ADFE1258A80, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF6DC9F581F7BC6, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFFCB9505E115842, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FECB9505E115842, %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Qubit* inttoptr (i64 6 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FEABCEF3EE79C5C, %Qubit* inttoptr (i64 7 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FFACD437FB19107, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFCAB482B6D63F00, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FFACD437FB19107, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFFABCEF3EE79C5C, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FEABCEF3EE79C5C, %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Qubit* inttoptr (i64 8 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFE907F9D441E121, %Qubit* inttoptr (i64 9 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FF098FBFFC03F20, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FF111FEA907DBF0, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FF098FBFFC03F20, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FF907F9D441E120, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF017B8D3F1843C, %Qubit* inttoptr (i64 11 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFE907F9D441E121, %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Qubit* inttoptr (i64 10 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FF4DF220436C666, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FE10B6540359AC8, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FF4DF220436C666, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x400017B8D3F1843C, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF017B8D3F1843C, %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Qubit* inttoptr (i64 12 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF383096A0C0D54, %Qubit* inttoptr (i64 13 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FE7B8CF8A166ED7, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FFA8B271E71EB58, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FE7B8CF8A166ED7, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x400383096A0C0D54, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF383096A0C0D54, %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Qubit* inttoptr (i64 14 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FF78D0FB2FB6A6F, %Qubit* inttoptr (i64 15 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FEB9E75D71CB1E7, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FF6A580D16BA848, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FEB9E75D71CB1E7, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xC0078D0FB2FB6A6F, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FF78D0FB2FB6A6F, %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Qubit* inttoptr (i64 16 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFED84D5B7D7F31C, %Qubit* inttoptr (i64 17 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF1DEE8F9533D95, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFED0C496BC3BE10, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF1DEE8F9533D95, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FFD84D5B7D7F31C, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFED84D5B7D7F31C, %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Qubit* inttoptr (i64 18 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF8AC26B49FAF5D, %Qubit* inttoptr (i64 19 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFED27E12AA7C95D, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF51C157DE090D0, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFED27E12AA7C95D, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x4008AC26B49FAF5C, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF8AC26B49FAF5D, %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Qubit* inttoptr (i64 20 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FC0588816E549C6, %Qubit* inttoptr (i64 21 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF28A215691DD0D, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFEA5F67F6C94030, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF28A215691DD0D, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFD0588816E549C8, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FC0588816E549C6, %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Qubit* inttoptr (i64 22 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FE590B0D7A3C064, %Qubit* inttoptr (i64 23 to %Qubit*))
  call void @__quantum__qis__h__body(%Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FE726044B942816, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__ry__body(double 0xBFF921FB54442D18, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FFB1DF25CF4321C, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FE726044B942816, %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Qubit* inttoptr (i64 25 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0xBFF590B0D7A3C064, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__rz__body(double 0x3FE590B0D7A3C064, %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__cnot__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Qubit* inttoptr (i64 24 to %Qubit*))
  call void @__quantum__qis__mz__body(%Qubit* null, %Result* inttoptr (i64 26 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 1 to %Qubit*), %Result* inttoptr (i64 27 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 2 to %Qubit*), %Result* inttoptr (i64 28 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 3 to %Qubit*), %Result* inttoptr (i64 29 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 4 to %Qubit*), %Result* inttoptr (i64 30 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 5 to %Qubit*), %Result* inttoptr (i64 31 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 6 to %Qubit*), %Result* inttoptr (i64 32 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 7 to %Qubit*), %Result* inttoptr (i64 33 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 8 to %Qubit*), %Result* inttoptr (i64 34 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 9 to %Qubit*), %Result* inttoptr (i64 35 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 10 to %Qubit*), %Result* inttoptr (i64 36 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 11 to %Qubit*), %Result* inttoptr (i64 37 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 12 to %Qubit*), %Result* inttoptr (i64 38 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 13 to %Qubit*), %Result* inttoptr (i64 39 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 14 to %Qubit*), %Result* inttoptr (i64 40 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 15 to %Qubit*), %Result* inttoptr (i64 41 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 16 to %Qubit*), %Result* inttoptr (i64 42 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 17 to %Qubit*), %Result* inttoptr (i64 43 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 18 to %Qubit*), %Result* inttoptr (i64 44 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 19 to %Qubit*), %Result* inttoptr (i64 45 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 20 to %Qubit*), %Result* inttoptr (i64 46 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 21 to %Qubit*), %Result* inttoptr (i64 47 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 22 to %Qubit*), %Result* inttoptr (i64 48 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 23 to %Qubit*), %Result* inttoptr (i64 49 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 24 to %Qubit*), %Result* inttoptr (i64 50 to %Result*))
  call void @__quantum__qis__mz__body(%Qubit* inttoptr (i64 25 to %Qubit*), %Result* inttoptr (i64 51 to %Result*))
  call void @__quantum__rt__array_record_output(i64 26, i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 25 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 24 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 23 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 22 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 21 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 20 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 19 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 18 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 17 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 16 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 15 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 14 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 13 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 12 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 11 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 10 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 9 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 8 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 7 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 6 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 5 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 4 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 3 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 2 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 1 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* null, i8* null)
  call void @__quantum__rt__array_record_output(i64 26, i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 51 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 50 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 49 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 48 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 47 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 46 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 45 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 44 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 43 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 42 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 41 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 40 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 39 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 38 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 37 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 36 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 35 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 34 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 33 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 32 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 31 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 30 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 29 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 28 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 27 to %Result*), i8* null)
  call void @__quantum__rt__result_record_output(%Result* inttoptr (i64 26 to %Result*), i8* null)
  ret void
}

declare void @__quantum__rt__initialize(i8*)

declare void @__quantum__qis__h__body(%Qubit*)

declare void @__quantum__qis__rz__body(double, %Qubit*)

declare void @__quantum__qis__ry__body(double, %Qubit*)

declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)

declare void @__quantum__qis__mz__body(%Qubit*, %Result* writeonly) #1

declare void @__quantum__rt__array_record_output(i64, i8*)

declare void @__quantum__rt__result_record_output(%Result*, i8*)

attributes #0 = { "entry_point" "num_required_qubits"="26" "num_required_results"="52" "output_labeling_schema" "qir_profiles"="custom" }
attributes #1 = { "irreversible" }
