# .github/workflows/publish.yml
name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
          pip install uv
          uv sync --all-extras --dev
      - name: Test
        run: |
          uv run nox -s test_translate

      - name: Generate lock file
        run: uv lock

      - name: Build package
        run: uv build

      - name: Publish package
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.MQSS_PYPI_API_TOKEN }}
        run: uv publish -v -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}